### ISSUE TITLE
add a licence

### ISSUE THREAD

**Issue by adrianN** [emk/heroku-rust-cargo-hello#5]
Without a licence file cloning this repository and deploying it to heroku would violate copyright, I think.

**Comment by emk** [comment]
I'm sorry, this somehow slipped through my GitHub notifications without me seeing it!

As far as I'm concerned and your legal system permits, this example code is in the public domain. Anybody who sees this, please feel free to submit a PR with a top-level `LICENSE.txt` containing a copy of the [CC0 text license](https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt). I'll accept it and sign off on it.

**Comment by emk** [comment]
Fixed in #8.
